services:
  Geekimo\Bundle\RethinkDBBundle\Services\Connection:
    public: true
    factory: [Geekimo\Bundle\RethinkDBBundle\Services\Factory, getConnection]
    class: Geekimo\Bundle\RethinkDBBundle\Services\Connection
    arguments:
      $parameters: '%rethink_db%'
  Geekimo\Bundle\RethinkDBBundle\Services\Repository:
    public: true
    class: Geekimo\Bundle\RethinkDBBundle\Services\Repository
  rethinkdb.connection:
    alias: Geekimo\Bundle\RethinkDBBundle\Services\Connection
  rethinkdb.repository:
    alias: Geekimo\Bundle\RethinkDBBundle\Services\Repository