services:
  Geekimo\Bundle\RethinkDBBundle\Service\Connection:
    public: true
    factory: [Geekimo\Bundle\RethinkDBBundle\Service\Factory, getConnection]
    class: Geekimo\Bundle\RethinkDBBundle\Service\Connection
    arguments:
      $parameters: '%rethink_db%'
  Geekimo\Bundle\RethinkDBBundle\Service\Repository:
    public: true
    class: Geekimo\Bundle\RethinkDBBundle\Service\Repository
    arguments:
      $connection: '@rethinkdb.connection'
  rethinkdb.connection:
    public: true
    alias: Geekimo\Bundle\RethinkDBBundle\Service\Connection
  rethinkdb.repository:
    public: true
    alias: Geekimo\Bundle\RethinkDBBundle\Service\Repository