services:
  Geekimo\Bundle\RethinkDBBundle\Connection:
    public: true
    factory: [Geekimo\Bundle\RethinkDBBundle\Services\RethinkDBFactory, getConnection]
    class: Geekimo\Bundle\RethinkDBBundle\Connection
    arguments:
      $parameters: '%rethink_db%'